const CreateNewWalletRouter = {
    CREATE_NEW_WALLET_SCREEN: 'CREATE_NEW_WALLET_SCREEN',
    RECOVERY_PHRASE_SCREEN: 'RECOVERY_PHRASE_SCREEN',
    DOUBLE_CHECK_IT_SCREEN: 'DOUBLE_CHECK_IT_SCREEN',
    IMPORT_PHRASE_SCREEN: 'IMPORT_PHRASE_SCREEN',
    CHOOSE_PIN_SCREEN: 'CHOOSE_PIN_SCREEN',
    CONFIRM_PIN_SCREEN: 'CONFIRM_PIN_SCREEN',
};

export default CreateNewWalletRouter;
