const CreateNewWalletRouter = {
    CREATE_NEW_WALLET_SCREEN: 'CREATE_NEW_WALLET_SCREEN',
    RECOVERY_PHRASE_SCREEN: 'RECOVERY_PHRASE_SCREEN',
    DOUBLE_CHECK_IT_SCREEN: 'DOUBLE_CHECK_IT_SCREEN',
    IMPORT_PHRASE_SCREEN: 'IMPORT_PHRASE_SCREEN',
    CONNECT_LEDGER_SCREEN: 'CONNECT_LEDGER_SCREEN',
    ADD_KEY_SCREEN: 'ADD_KEY_SCREEN'
};

export default CreateNewWalletRouter;
