export enum ERequestKeys {
  validatorsDetail = 'validatorsDetail',
  validators = 'validators',
  accountDelegation = 'accountDelegation',
  stakingRewards = 'stakingRewards',
  latestPrice = 'latestPrice',
  priceHistory = 'priceHistory',
  tokenInfoWithBalance = 'tokenInfoWithBalance',
  tokenInfo = 'tokenInfo',
  accountInfo = 'accountInfo',
  listAccountInfo = 'listAccountInfo',
  configurations = 'configurations',
  nftsInfo = 'nftsInfo',
  deploysStatus = 'deploysStatus',
  releaseNotes = 'releaseNotes',
  news = 'news',
}
