const MainRouter = {
  HOME_TAB: 'HOME_TAB',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  ADD_CUSTOM_TOKEN_SCREEN: 'ADD_CUSTOM_TOKEN_SCREEN',
  CONFIRM_SEND_SCREEN: 'CONFIRM_SEND_SCREEN',
  SEND_SCREEN: 'SEND_SCREEN'
};
export default MainRouter;
