const MainRouter = {
  HOME_TAB: 'HOME_TAB',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  ADD_CUSTOM_TOKEN_SCREEN: 'ADD_CUSTOM_TOKEN_SCREEN',
  CONFIRM_SEND_SCREEN: 'CONFIRM_SEND_SCREEN',
  SEND_SCREEN: 'SEND_SCREEN',
  RECEIVE_SCREEN: 'RECEIVE_SCREEN',
  HISTORIES_SCREEN: 'HISTORIES_SCREEN',
  NFTDETAIL_SCREEN: 'NFTDETAIL_SCREEN',
  VALIDATOR_SCREEN: 'VALIDATOR_SCREEN',
  TRANSFER_HISTORY_SCREEN: 'TRANSFER_HISTORY_SCREEN',
  STAKING_CONFIRM_SCREEN: 'STAKING_CONFIRM_SCREEN',
  IMPORT_ACCOUNT_SCREEN: 'IMPORT_ACCOUNT_SCREEN',
  SHOW_RECOVERY_PHRASE_SCREEN: 'SHOW_RECOVERY_PHRASE_SCREEN',
  SHOW_PRIVATE_KEY_SCREEN: 'SHOW_PRIVATE_KEY_SCREEN',
};
export default MainRouter;
