const StakingRouter = {
  MAIN: 'Staking',
  STAKING_SCREEN: 'STAKING_SCREEN',
  STAKING_CONFIRM_SCREEN: 'STAKING_CONFIRM_SCREEN',
  UNDELEGATE_FORM_SCREEN: 'UNDELEGATE_FORM_SCREEN',
};
export default StakingRouter;
