# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  #ensure_git_status_clean
  #git_pull
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    #slack(message: ":rocket: *I am going to bump a new build to Testflight!* :rocket:")
    increment_build_number(xcodeproj: "CasperDash.xcodeproj")
    build_app(
        workspace: "CasperDash.xcworkspace",
        scheme: "CasperDash",
        export_xcargs: "-allowProvisioningUpdates"
    )
    pilot( api_key_path: "fastlane/release.json" )  

    slack(message: ":rocket: *New build has been uploaded to Testflight!* :rocket:")
  end
end

platform :ios do
  desc "Push a new staging build to TestFlight"
  lane :staging do
    slack(message: ":rocket: *I am going to bump a new staging build to Testflight!* :rocket:")
    increment_build_number(xcodeproj: "CasperDash.xcodeproj")
    build_app(
        workspace: "CasperDash.xcworkspace",
        scheme: "CasperDash-staging",
        export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
         skip_waiting_for_build_processing: false 
    )

    slack(message: ":rocket: *New staging build has been uploaded to Testflight!* :rocket:")
  end
end

platform :ios do
  lane :tests do
    build_ios_app(workspace: "CasperDash.xcworkspace",
              scheme:"CasperDash-staging")
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :bump do
    upload_to_testflight(
        skip_waiting_for_build_processing: false 
    )

    slack(message: ":rocket: *New build has been uploaded to Testflight!* :rocket:")
  end
end
